name = "OkValueSegments"
uuid = "bf75f91d-8d33-4f2c-bf9d-6eaba12b5f3c"
authors = ["okatsn <okatsn@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
